
package com.local.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IBankService", targetNamespace = "http://service.bank.yinhai.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IBankService {


    /**
     * 
     * @param paramXml
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "doBankService", targetNamespace = "http://service.bank.yinhai.com/", className = "com.local.client.DoBankService")
    @ResponseWrapper(localName = "doBankServiceResponse", targetNamespace = "http://service.bank.yinhai.com/", className = "com.local.client.DoBankServiceResponse")
    public String doBankService(
        @WebParam(name = "paramXml", targetNamespace = "")
        String paramXml);

}
